In [3]:
import pandas as pd
import numpy as np

Задание 1 (0.25 балла): открыть данные из файла.

In [4]:
data = pd.read_csv('supermarket_sales.csv')

Задание 2 (0.75 балла): детальное изучение данных.

In [5]:
## первые пять строчек нашего DataFrame
data.head(5)

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1  
1  10:29         Cash   76.40                 4.761905        3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905       23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905       30.2085     5.3

In [6]:
## последние пять строчек
data.tail(5)

Invoice ID Branch       City Customer type  Gender         Product line  \
995  233-67-5758      C  Naypyitaw        Normal    Male    Health and beauty   
996  303-96-2227      B   Mandalay        Normal  Female   Home and lifestyle   
997  727-02-1313      A     Yangon        Member    Male   Food and beverages   
998  347-56-2442      A     Yangon        Normal    Male   Home and lifestyle   
999  849-09-3807      A     Yangon        Member  Female  Fashion accessories   

     Unit price  Quantity   Tax 5%      Total       Date   Time  Payment  \
995       40.35         1   2.0175    42.3675  1/29/2019  13:46  Ewallet   
996       97.38        10  48.6900  1022.4900   3/2/2019  17:16  Ewallet   
997       31.84         1   1.5920    33.4320   2/9/2019  13:22     Cash   
998       65.82         1   3.2910    69.1110  2/22/2019  15:33     Cash   
999       88.34         7  30.9190   649.2990  2/18/2019  13:28     Cash   

       cogs  gross margin percentage  gross income  Rating  
995   40.35                 4.761905        2.0175     6.2  
996  973.80                 4.761905       48.6900     4.4  
997   31.84                 4.761905        1.5920     7.7  
998   65.82                 4.761905        3.2910     4.1  
999  618.38                 4.761905       30.9190     6.6

In [7]:
## размерность (сколько признаков и сколько строчек мы имеем в данных)
data.shape

(1000, 17)

In [8]:
## названия наших признаков
data.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [9]:
## типы данных наших признаков. То есть это целые числа, дробные, строчки или что ещё
data.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [10]:
## вывела общую информацию про весь DataFrame
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               1000 non-null   object 
 1   Branch                   1000 non-null   object 
 2   City                     1000 non-null   object 
 3   Customer type            1000 non-null   object 
 4   Gender                   1000 non-null   object 
 5   Product line             1000 non-null   object 
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64  
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object 
 11  Time                     1000 non-null   object 
 12  Payment                  1000 non-null   object 
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  

In [11]:
## общую статистическую информацию про наши данных (например, через describe)
data.describe()

Unit price     Quantity       Tax 5%        Total        cogs  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000   
mean     55.672130     5.510000    15.379369   322.966749   307.58738   
std      26.494628     2.923431    11.708825   245.885335   234.17651   
min      10.080000     1.000000     0.508500    10.678500    10.17000   
25%      32.875000     3.000000     5.924875   124.422375   118.49750   
50%      55.230000     5.000000    12.088000   253.848000   241.76000   
75%      77.935000     8.000000    22.445250   471.350250   448.90500   
max      99.960000    10.000000    49.650000  1042.650000   993.00000   

       gross margin percentage  gross income      Rating  
count              1000.000000   1000.000000  1000.00000  
mean                  4.761905     15.379369     6.97270  
std                   0.000000     11.708825     1.71858  
min                   4.761905      0.508500     4.00000  
25%                   4.761905      5.924875     5.50000  
50%                   4.761905     12.088000     7.00000  
75%                   4.761905     22.445250     8.50000  
max                   4.761905     49.650000    10.00000

Задание 3 (1 балл): перевести признак Date в единицы измерения времени.

In [12]:
data['Date'] = pd.to_datetime(data['Date'])
data.head()

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715 2019-01-05   
1  Electronic accessories       15.28         5   3.8200   80.2200 2019-03-08   
2      Home and lifestyle       46.33         7  16.2155  340.5255 2019-03-03   
3       Health and beauty       58.22         8  23.2880  489.0480 2019-01-27   
4       Sports and travel       86.31         7  30.2085  634.3785 2019-02-08   

    Time      Payment    cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1  
1  10:29         Cash   76.40                 4.761905        3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905       23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905       30.2085     5.3

Задание 4 (1 балл): индексация по датам.

In [13]:
data.set_index('Date', inplace=True)
data.head()

Invoice ID Branch       City Customer type  Gender  \
Date                                                              
2019-01-05  750-67-8428      A     Yangon        Member  Female   
2019-03-08  226-31-3081      C  Naypyitaw        Normal  Female   
2019-03-03  631-41-3108      A     Yangon        Normal    Male   
2019-01-27  123-19-1176      A     Yangon        Member    Male   
2019-02-08  373-73-7910      A     Yangon        Normal    Male   

                      Product line  Unit price  Quantity   Tax 5%     Total  \
Date                                                                          
2019-01-05       Health and beauty       74.69         7  26.1415  548.9715   
2019-03-08  Electronic accessories       15.28         5   3.8200   80.2200   
2019-03-03      Home and lifestyle       46.33         7  16.2155  340.5255   
2019-01-27       Health and beauty       58.22         8  23.2880  489.0480   
2019-02-08       Sports and travel       86.31         7  30.2085  634.3785   

             Time      Payment    cogs  gross margin percentage  gross income  \
Date                                                                            
2019-01-05  13:08      Ewallet  522.83                 4.761905       26.1415   
2019-03-08  10:29         Cash   76.40                 4.761905        3.8200   
2019-03-03  13:23  Credit card  324.31                 4.761905       16.2155   
2019-01-27  20:33      Ewallet  465.76                 4.761905       23.2880   
2019-02-08  10:37      Ewallet  604.17                 4.761905       30.2085   

            Rating  
Date                
2019-01-05     9.1  
2019-03-08     9.6  
2019-03-03     7.4  
2019-01-27     8.4  
2019-02-08     5.3

1. Как Вы думаете, для чего это требуется? 
2. Насколько это необходимо? 
3. Можно ли это не делать? Можно ли сделать индексацию не по Date?

1,2) Индексация по датам требуется чтобы облегчить работу с временными рядами и использование методов временных рядов, таких как скользящие средние или экспоненциальное сглаживание. 

3) Конечно, можно использовать другой признак в качестве индекса, если это имеет смысл для конкретной задачи (но не для нашей). Например, если мы анализируем данные о продажах по магазинам, то может быть логично индексировать данные по признаку Store.

Задание 5 (1 балл): проверка на пропущенные значения.

In [14]:
data.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

Задание 6 (1 балл): убрать пропущенные значения из данных. На примере признака Unit price.

In [15]:
data.dropna(subset=['Unit price'], inplace=True)

data.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

1) В какое случае можно удалить строчки с пустыми значениями, а в каком случае не стоит этого делать? Если нет убирать пустые значения, то что с ними делать? На что их заменить? Есть какие-то идеи?

Если пропущенные значения не могут быть удалены, то их можно заменить на другое значение. Например, можно заменить все пропущенные значения в признаке Unit price на среднее значение этого признака. Удаление или замена пропущенных значений может привести к потере информации, поэтому необходимо внимательно анализировать данные и принимать решение о том, как лучше поступить в каждом конкретном случае.

2) Как быть с выбросами/аномалиями в данных? Что это такое, Вы знаете? Как их найти/определить? В данном домашнем задании это не требуется, но в общем случае бывает крайне эффективно поработать и с этим тоже.Как найти возможные выбросы/аномалии? Если они есть, то что с ними делать?

 Выбросы/аномалии - это значения, которые сильно отличаются от остальных значений в наборе данных. Они могут быть вызваны ошибками измерения, ошибками ввода данных или являться реальными, но редкими событиями.

Чтобы найти возможные выбросы или аномалии в данных, можно использовать различные методы. Некоторые из них:

Графический анализ: Постройте графики, такие как гистограммы, ящики с усами (boxplot) или диаграммы рассеяния (scatterplot), чтобы визуально идентифицировать значения, которые находятся далеко от основной массы значений.

Статистический анализ: Используйте статистические методы, такие как квартили, стандартное отклонение или межквартильный размах, чтобы определить значения, которые сильно отличаются от среднего значения.

Машинное обучение: Используйте методы машинного обучения, такие как кластерный анализ или алгоритмы обнаружения выбросов, чтобы идентифицировать группы данных, которые сильно отличаются от других.

Что делать с выбросами зависит от конкретной ситуации и целей анализа данных. В некоторых случаях, выбросы можно просто игнорировать, если они вызваны ошибками измерения или являются редкими событиями. В других случаях, выбросы могут быть важными событиями, которые необходимо учитывать в анализе данных. В таких случаях, можно использовать методы, такие как трансформация данных, чтобы уменьшить влияние выбросов или модельные подходы, чтобы выделить группы данных, которые сильно отличаются от других.

Задание 7 (1 балл): придумать новый признак (колонку) для наших данных.

Еще один возможный признак, который можно добавить в данные - это время суток, когда была совершена покупка. Для этого, можно использовать информацию о времени покупки, которая уже есть в наших данных. Например, можно разделить сутки на несколько временных интервалов (например, утро, день, вечер, ночь) и присвоить каждой покупке соответствующий интервал.

In [16]:
data['Time'] = pd.to_datetime(data['Time'])

## здесь я вычислила время суток
bins = [0, 6, 12, 18, 24]
labels = ['ночь', 'утро', 'день', 'вечер']
data['время суток'] = pd.cut(data['Time'].dt.hour, bins=bins, labels=labels, include_lowest=True)

## тут вывела первые 5 строк таблицы с новым признаком
data.head(5)

Invoice ID Branch       City Customer type  Gender  \
Date                                                              
2019-01-05  750-67-8428      A     Yangon        Member  Female   
2019-03-08  226-31-3081      C  Naypyitaw        Normal  Female   
2019-03-03  631-41-3108      A     Yangon        Normal    Male   
2019-01-27  123-19-1176      A     Yangon        Member    Male   
2019-02-08  373-73-7910      A     Yangon        Normal    Male   

                      Product line  Unit price  Quantity   Tax 5%     Total  \
Date                                                                          
2019-01-05       Health and beauty       74.69         7  26.1415  548.9715   
2019-03-08  Electronic accessories       15.28         5   3.8200   80.2200   
2019-03-03      Home and lifestyle       46.33         7  16.2155  340.5255   
2019-01-27       Health and beauty       58.22         8  23.2880  489.0480   
2019-02-08       Sports and travel       86.31         7  30.2085  634.3785   

                          Time      Payment    cogs  gross margin percentage  \
Date                                                                           
2019-01-05 2023-04-23 13:08:00      Ewallet  522.83                 4.761905   
2019-03-08 2023-04-23 10:29:00         Cash   76.40                 4.761905   
2019-03-03 2023-04-23 13:23:00  Credit card  324.31                 4.761905   
2019-01-27 2023-04-23 20:33:00      Ewallet  465.76                 4.761905   
2019-02-08 2023-04-23 10:37:00      Ewallet  604.17                 4.761905   

            gross income  Rating время суток  
Date                                          
2019-01-05       26.1415     9.1        день  
2019-03-08        3.8200     9.6        утро  
2019-03-03       16.2155     7.4        день  
2019-01-27       23.2880     8.4       вечер  
2019-02-08       30.2085     5.3        утро

В моем случае, со временем суток, это может помочь определить, в какое время суток наиболее популярны различные товары и категории товаров, что может быть полезно при планировании распределения товаров в магазине и управлении запасами

Задание 8 (1 балл): фильтрация наших данных.

In [17]:
# фильтрация данных по условию
k = data[(data['City'] == 'Yangon') & (data['Payment'] == 'Ewallet')]

# вывела количество строк, удовлетворяющих условиям фильтрации
print(f"Количество строк: {len(k)}")


Количество строк: 126


### Numpy

Задание 9 (0.25 балла): создать нулевой вектор размерность 10

In [18]:
# создала нулевой вектор размерностью 10
a = np.zeros(10)

# вывела этот вектор
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Задание 10 (0.25 балла): создать матрицу 3x3 со значениями в диапазоне от 0 до 8.

In [19]:
# сначала я создала одномерный массив с элементами от 0 до 8
a = np.arange(9)
# преобразовала его в матрицу 3x3
m = a.reshape(3, 3)
print(m)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Задание 11 (0.5 балла): создать матрица 10x10 со случайными значениями и найти минимальный и максимальный элементы.

In [20]:
# создала матрицу 10x10 со случайными значениями
m = np.random.rand(10, 10)

# тут вывела минимальное и максимальное значение элементов в матрице
min = np.min(m)
max = np.max(m)

print(min)
print(max)


0.00013530031580966106
0.9583282575826718


Задание 12 (1 балл): создать матрицу 10x10, в которой все значения нули, кроме границ. Граничные элементы пускай будут равны единицам.

In [21]:
# заполнила и создала матрицу нулями
m = np.zeros((10, 10))

# границы - единички
m[0, :] = 1
m[-1, :] = 1
m[:, 0] = 1
m[:, -1] = 1

print(m)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Задание 13 (0.5 балла): поменять местами две строчки матрицы.

In [22]:
# Здесь пишу номера строк
i, j = 0, 5
# Поменяла местами две строки
m[[i, j]] = m[[j, i]]

print(m)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Задание 14 (0.25 балла): создать массив из 50 элементов (заполнить случайными целыми числами от 0 до 10, 10 не включаем) и для него найти среднее, стандартное отклонение и медиану.

In [23]:
# Создала массив из 50 случайных целых чисел от 0 до 9
a = np.random.randint(0, 10, 50)

# Нашла среднее значение
k = np.mean(a)

# Нашла стандартное отклонение
s = np.std(a)

# Нашла медиану
med = np.median(a)

print("Массив:", a)
print("Среднее значение:", k)
print("Стандартное отклонение:", s)
print("Медиана:", med)


Массив: [5 8 7 0 3 3 3 5 2 5 4 3 7 2 1 0 3 4 2 4 7 1 9 7 6 7 2 6 3 3 7 3 5 2 8 1 1
 5 8 5 8 0 3 6 8 8 4 3 7 2]
Среднее значение: 4.32
Стандартное отклонение: 2.5095019426172995
Медиана: 4.0


Задание 15 (0.25 балла): посчитать определитель матрицы 5x5.

In [24]:
# ОПЯТЬ создала матрицу и заполнила ее рандомными числами от 0 до 9
a = np.random.randint(low=0, high=10, size=(5, 5))

# Воспользовалась уже встроенной функциейю (схитрила)
det_a= np.linalg.det(a)

print(a)
print(det_a)



[[9 3 8 9 6]
 [9 4 1 0 7]
 [7 1 0 2 5]
 [1 0 3 9 9]
 [6 9 1 0 3]]
12263.999999999996
